### ISSUE TITLE
HOW to get 

### ISSUE THREAD

**Issue by pawelk1337** [Yleisradio/github-action-trello-integration#5]
```  
TRELLO_BOARD_ID: BOARD-24-CHAR-LONG-ID
and
TRELLO_LIST_ID: LIST-24-CHAR-LONG-ID
```

**Comment by rpsu** [comment]
README has a section dedicated to this:
https://github.com/Yleisradio/github-action-trello-integration#how-do-i-find-the-necessary-trello-board-and-list-ids
