### ISSUE TITLE
Issue with TRELLO_BOARD_ID pattern does not match the pattern

### ISSUE THREAD

**Issue by marlonmantilla** [Yleisradio/github-action-trello-integration#6]
Hey everyone, I'm sorry if this question is too basic, I'm new to Github actions and I'm having this issue. 

![Captura de Pantalla 2022-03-10 a la(s) 12 40 06 p m](https://user-images.githubusercontent.com/238278/157722765-f1b3dfd3-ee33-47d6-b6c7-87c052e84c8a.png)

I make sure to create secrets variables -> 

![Captura de Pantalla 2022-03-10 a la(s) 12 41 18 p m](https://user-images.githubusercontent.com/238278/157722972-1666d102-d2ab-49fc-89a7-17bed6d14f58.png)

Does anyone knows what could be missing here, the error is kind of confusing `TRELLO_BOARD_ID pattern does not match the pattern.`  I make sure the board id was setup as the README files shows and the id does have 24 characters length. 

Any ideas ?

**Comment by rpsu** [comment]
Your environment variables are a bit off, they still contain the strings that should be replaced.

for these you need to have ID's from Trello side:
![Screenshot 2022-03-11 at 10 12 53](https://user-images.githubusercontent.com/1099454/157828388-ee31771c-75c7-444d-865a-c47d04c46137.png)

this is instructed in the [README.md](https://github.com/Yleisradio/github-action-trello-integration#how-do-i-find-the-necessary-trello-board-and-list-ids). ID'are 24 character long strings.

          TRELLO_BOARD_ID: YOUR-BOARD-ID
          TRELLO_SOURCE_LIST_ID: YOUR-SOURCE-LIST-ID
          TRELLO_TARGET_LIST_ID: YOUR-TARGET-LIST-ID
