### ISSUE TITLE
Error: 401 async text()

### ISSUE THREAD

**Issue by alexmigf** [Yleisradio/github-action-trello-integration#7]
I'm getting this error using this action:

![Screenshot from 2024-02-08 12-34-55](https://github.com/Yleisradio/github-action-trello-integration/assets/533273/f11ffa24-3d65-439e-8d38-b76aa560102b)

Any clue on what could be the issue?

**Comment by RishabhTayal** [comment]
getting same error.

**Comment by RishabhTayal** [comment]
You need to use Trello token instead of Trello secret. Its solved for me.

**Comment by rpsu** [comment]
yes, as described in the README use token in `TRELLO_API_TOKEN`, not the Trello secret.
